language: python

python:
    - "2.7"

install: "pip install -r requirements.txt"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - coverage erase
  - make test
  - coverage combine
  - coverage report -m

after_success:
  - coveralls
