#!/usr/bin/env python

import logging
import sys
from getopt import getopt

import opscli.ovsdb as ovsdb
from opscli.cli import Opscli

DEFAULT_SERVER = 'unix:/var/run/openvswitch/db.sock'
MODULE_PATHS = ('commands', 'tokens')


def usage():
    print "Usage: ops-cli [-h] [-s <server>] [-d <debug options>,...]"
    sys.exit()


def main(args):
    ovsdb_server = DEFAULT_SERVER
    # TODO(bluecmd): Switch to argparse?
    opts, args = getopt(args, 'hs:d:')
    for opt, arg in opts:
        if opt == '-h':
            usage()
        elif opt == '-s':
            ovsdb_server = arg
        elif opt == '-d':
            # TODO(bluecmd): Set logging level
            pass

    ovsdb_obj = ovsdb.Ovsdb(server=ovsdb_server)
    try:
        ovsdb_obj.connect()
    except:
        logging.exception('Unable to connect to %s', ovsdb)
    cli = Opscli(ovsdb_obj, module_paths=MODULE_PATHS)
    cli.start()

if __name__ == '__main__':
    main(sys.argv[1:])
